version: '3.8'

services:
    user:
        build:
            context: ./userService
        image: microservice/demo/user
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=Microservice-demo-user
        ports:
            - 8080:50051
        depends_on:
            - mongo

    project:
        build:
            context: ./projectService
        image: microservice/demo/project
        restart: "no"
        environment:
            - DB_URI=mysql+mysqldb://root:password@mysql:3306/microservice-project
        ports:
            - 8081:50052
        depends_on:
            - mysql
            - user

    task:
        build:
            context: ./taskService
        image: microservice/demo/task
        restart: "no"
        entrypoint: [./init]
        environment:
            - USER_ADDRESS=user:50051
            - PROJECT_ADDRESS=project:50052
            - DB_URI=postgres://postgres:password@postgresql:5432/microservice-task
        ports:
            - 8082:50053
        depends_on:
            - postgresql
            - user
            - project

    api:
        build:
            context: ./apiService
        image: microservice/demo/api
        restart: "no"
        environment:
            - USER_ADDRESS=user:50051
            - PROJECT_ADDRESS=project:50052
            - TASK_ADDRESS=task:50053
        ports:
            - 8083:50059
        command: serve
        depends_on:
            - user
            - project
            - task


    api-gateway:
        image: microservice/demo/api
        restart: "no"
        environment:
            - HOST=api
            - PORT=50059
            - PROXY_PORT=9090
        ports:
            - 9090:9090
        command: proxy
        depends_on:
            - api
    
    postgresql:
        image: postgres
        restart: "no"
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: microservice-task
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgresdb:/var/lib/postgresql/data/

    mysql:
        image: mysql:5.7
        restart: "no"
        environment:
            MYSQL_DATABASE: microservice-project
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - mysqldb:/var/lib/mysql

    mongo:
        image: mongo
        restart: "no"
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

volumes:
    postgresdb:
    mysqldb:
    mongodb:
    mongodb_config: