# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: task/task.proto for package 'demo_task'

require 'grpc'
require 'task/task_pb'

module DemoTask
  module TaskSvc
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'demo_task.TaskSvc'

      rpc :createTask, ::DemoTask::CreateTaskRequest, ::DemoTask::TaskResponse
      rpc :updateTask, ::DemoTask::UpdateTaskRequest, ::DemoTask::TaskResponse
      rpc :listTasks, ::DemoTask::ListTasksRequest, ::DemoTask::ListTasksResponse
    end

    Stub = Service.rpc_stub_class
  end
end
