# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task/task.proto

require 'google/protobuf'

require 'project/project_pb'
require 'user/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("task/task.proto", :syntax => :proto3) do
    add_message "demo_task.CreateTaskRequest" do
      optional :user_id, :string, 1
      optional :name, :string, 2
      optional :project_id, :string, 3
      optional :tag_id, :string, 4
      optional :assigned_user_id, :string, 5
    end
    add_message "demo_task.TaskResponse" do
      optional :user_id, :string, 1
      optional :name, :string, 2
      optional :project, :message, 3, "demo_project.ProjectResponse"
      optional :tag, :message, 4, "demo_project.TagResponse"
      optional :assigned_user, :message, 5, "demo_user.UserResponse"
    end
  end
end

module DemoTask
  CreateTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.CreateTaskRequest").msgclass
  TaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo_task.TaskResponse").msgclass
end
